repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241  # Use the latest stable version if available
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991  # Update this to the latest stable mypy version if needed
    hooks:
      - id: mypy
