repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241  # Use the latest stable version if available
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Updated to latest stable version
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive"]
        additional_dependencies: [
          'pydantic>=2.0.0',
          'bson',
          'colorlog',
          'pytest',
          'types-PyYAML',
          'types-bleach',
        ]