name: Python Package CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p .uv/cache && chmod -R 777 .uv/cache

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-local-path: ".uv/cache"


      - name: Install package and depe^ndencies
        run: |
          uv pip install -e .
          uv pip install pytest mypy ruff build uv types-bleach types-PyYAML
          uv pip list  # optional diagnostic step

      - name: Run tests with pytest
        run: uv run pytest

      - name: Lint with ruff
        run: uv run ruff check .

      - name: Type check with mypy
        run: uv run mypy .

      - name: Build distributions
        run: python -m build
