name: Python Package CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package and dependencies
        run: |
          pip install .
          # Install testing, linting, type-checking, and uv dependencies
          pip install pytest mypy ruff build uv

      - name: Run tests with pytest
        run: pytest

      - name: Lint with ruff
        run: ruff .

      - name: Type check with mypy
        run: mypy .

      - name: Build distributions
        run: python -m build

      - name: Run uv for cross-version testing
        run: uv --all
